bnb-chain/canonical-bridge

.release/.changeset/dirty-carrots-call.md
=> chore: Add change log

.github/workflows/gh-cicd.yaml
=> chore: Use `vars` to read env variables

.github/workflows/gh-cicd.yaml, apps/canonical-bridge-ui/pages/_app.tsx, apps/canonical-bridge-ui/pages/index.tsx
=> feat: Add Index page

.github/workflows/gh-cicd.yaml
=> chore: Test

.github/workflows/gh-cicd.yaml
=> chore: Update github-pages cicd

.github/workflows/gh-cicd.yaml
=> chore: Update cicd

.github/workflows/gh-pages-cicd.yaml
=> chore: Push gh-pages to another repo

.github/workflows/gh-pages-cicd.yaml
=> chore: Update cide

packages/canonical-bridge-widget/src/modules/aggregator/adapters/meson/hooks/useTronContract.ts, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx
=> fix: Disable send button on invalid to address

.github/CODEOWNERS, .github/actions/setup/action.yaml, .github/workflows/alpha-sdk.yaml, .github/workflows/alpha-widget.yaml, .github/workflows/alpha.yaml, .github/workflows/gh-pages.yaml, .github/workflows/release.yaml
=> chore: Add code owners

packages/canonical-bridge-widget/src/core/constants/index.ts, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx
=> fix: Fix typo

packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx
=> feat: Evm to account address verification

.github/workflows/qa-deploy.yaml
=> chore: Fetch all history for repo

packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/InputValidationMessage.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx
=> fix: Fix input error message style

packages/canonical-bridge-widget/src/core/contract/hooks/useGetTokenBalance.ts, packages/canonical-bridge-widget/src/modules/aggregator/adapters/deBridge/hooks/useGetDeBridgeFees.ts
=> feat: Get native token balance based on selected chain

.github/workflows/release.yaml, .release/.changeset/unlucky-experts-joke.md
=> chore: Add .release to support trigger release workflow

.github/workflows/release.yaml, .release/.changeset/tender-pens-collect.md, .release/.changeset/unlucky-experts-joke.md
=> Release1024

.release/.changeset/pre.json, .release/.changeset/real-ways-try.md, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json
=> feat: Publish npm version

.github/workflows/qa-deploy.yaml, .github/workflows/release-server.yaml, .github/workflows/release.yaml
=> chore: Update timeout to 30m

apps/canonical-bridge-server/.eslintrc.js
=> chore: Test server cicd

packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/index.tsx
=> fix: Fix input focus issue

packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx
=> chore: Remove input icon

packages/canonical-bridge-widget/src/modules/wallet/WalletProvider.tsx
=> feat: Fix build error

.release/.changeset/green-camels-unite.md
=> chore: Test cicd

.github/workflows/release.yaml, .release/package.json
=> chore: Update release cicd

packages/canonical-bridge-widget/src/modules/aggregator/adapters/deBridge/hooks/useGetDeBridgeFees.ts
=> chore: Update debridge protocol fee error message

apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts
=> feat: Add btc sorting

packages/canonical-bridge-widget/src/modules/transfer/hooks/useLoadingBridgeFees.ts
=> fix: Fix reset meson fees

.release/.changeset/cool-grapes-crash.md
=> chore: Release new widget version

apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts
=> feat: Update default fromChainId

apps/canonical-bridge-server/src/main.ts
=> feat(canonical-bridge-server): Update keepalive timeout

packages/canonical-bridge-widget/docs/classname.md, packages/canonical-bridge-widget/src/core/theme/ThemeProvider.tsx, packages/space/src/modules/theme/internal/typography.ts
=> feat: Customize font family

packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ToSection/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/index.tsx
=> fix: Fix type

packages/canonical-bridge-widget/docs/customThemes.md, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/components/BaseModal.tsx
=> chore: Add demo code

common/config/rush/pnpm-lock.yaml, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/aggregator/shared/getTokenBalances.ts, packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx
=> fix: Show solana native token  balance

packages/canonical-bridge-widget/src/modules/aggregator/shared/sortTokens.ts
=> fix: Fix token balance sorting issue

apps/canonical-bridge-server/src/main.ts, apps/canonical-bridge-ui/core/components/ThemeProvider/index.tsx, apps/canonical-bridge-ui/pages/mainnet/index.tsx, packages/canonical-bridge-widget/docs/Custom Themes.md, packages/canonical-bridge-widget/src/core/components/IconImage/index.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/ChooseTokenModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/DestinationNetworkModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/SourceNetworkModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/components/BaseModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/components/ListItem.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/FromSection/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/NetWorkSection/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/MaxLink.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferButtonGroup/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/RouteInfo/OtherRouteError.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/RouteInfo/TokenInfoTooltip.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/index.tsx, packages/canonical-bridge-widget/src/modules/wallet/components/Dropdown/DropdownButton.tsx, packages/canonical-bridge-widget/src/modules/wallet/components/Dropdown/DropdownItem.tsx, packages/canonical-bridge-widget/src/modules/wallet/components/NetworkStatus/index.tsx, packages/canonical-bridge-widget/src/modules/wallet/components/ProfileMenu/index.tsx
=> feat: Widget classname test

.release/.changeset/new-glasses-happen.md
=> chore: Release new version

packages/canonical-bridge-widget/src/modules/wallet/WalletProvider.tsx
=> feat: Add tw for solana

.release/.changeset/little-books-raise.md, apps/canonical-bridge-ui/core/theme/dark.ts, apps/canonical-bridge-ui/core/theme/light.ts, packages/canonical-bridge-widget/src/core/components/StateModal/index.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/ChooseTokenModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/components/BaseModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/components/ListItem.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/NetWorkSection/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ReceiveInfo/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ToAccount/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/RouteInfo/RouteWrapper.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/index.tsx
=> feat: Adjust style and class name

packages/canonical-bridge-widget/src/core/theme/ThemeProvider.tsx
=> feat(canonical-bridge-widget): Fix default font family

packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/ChooseTokenModal.tsx
=> feat: Add address info to element

.release/.changeset/metal-forks-train.md
=> chore: Release version

packages/canonical-bridge-widget/src/modules/transfer/hooks/useSendTokenValidation.ts
=> fix: Check lower case address

packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx
=> test: Test fake token address

packages/canonical-bridge-sdk/src/debridge/index.ts, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx
=> test: Remove token address validation

packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx
=> test: Test meson token

packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx
=> test: Send debridge tx data to cbridge address

packages/canonical-bridge-sdk/src/debridge/index.ts
=> test: Revert debridge token address

packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx
=> test: Revert debridge contract address

packages/canonical-bridge-widget/src/core/components/IconImage/index.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/ChooseTokenModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/hooks/useSearch.ts, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/hooks/useTokenList.ts, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/RouteInfo/RouteName/index.tsx
=> feat: Fix token list sort issue

apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts
=> fix: Fix config path

.release/.changeset/many-houses-leave.md
=> chore: Release doc

.release/.changeset/cool-insects-walk.md, packages/canonical-bridge-sdk/__tests__/meson/index.test.ts, packages/canonical-bridge-sdk/src/meson/index.ts, packages/canonical-bridge-sdk/src/meson/types/index.ts
=> chore: Update meson validation for tron token

.release/.changeset/few-seals-press.md
=> chore: Update meson vadliation

apps/canonical-bridge-ui/token-config/mainnet/meson/config.json
=> chore: Remove unsupported tokens

apps/canonical-bridge-server/.env.example, apps/canonical-bridge-server/src/common/constants/index.ts, apps/canonical-bridge-server/src/module/bridge/bridge.controller.ts, apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/module/bridge/bridge.schedule.ts, apps/canonical-bridge-server/src/shared/web3/web3.interface.ts, apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> feat: Add Meson and Stargate server API endpoint

.github/workflows/server.yaml
=> feat: Update cicd

.github/workflows/server.yaml
=> chore: Update server cicd

apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts
=> fix: Fix procressor

packages/canonical-bridge-sdk/src/core/utils/number.ts, packages/canonical-bridge-sdk/src/layerZero/index.ts
=> fix: Fix sdk decimal issue

apps/canonical-bridge-server/src/common/constants/index.ts, apps/canonical-bridge-server/src/shared/web3/web3.interface.ts, apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> feat: Stargate endpoint ID

.release/.changeset/serious-cars-worry.md, apps/canonical-bridge-ui/next-env.d.ts, apps/canonical-bridge-ui/package.json, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/ChooseTokenModal.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SelectButton/TokenSelectButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/RouteInfo/RouteTitle.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/RouteInfo/TokenInfoTooltip.tsx
=> feat: Add more token info to token element

apps/canonical-bridge-server/Dockerfile
=> chore: Update dockerfile

apps/canonical-bridge-server/Dockerfile
=> chore: Running app as a non-root user

.github/CODEOWNERS, apps/canonical-bridge-ui/token-config/mainnet/chains.ts
=> fix: Update klaytn rpc

.release/.changeset/itchy-dots-enjoy.md, .release/.changeset/pre.json, packages/canonical-bridge-sdk/CHANGELOG.md, packages/canonical-bridge-sdk/package.json, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/aggregator/adapters/meson/MesonAdapter.ts
=> fix: Fix meson token display symbol issue

apps/canonical-bridge-server/src/module/token/token.schedule.ts, apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> feat: Add cache time to server

apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> feat: Remove simulation logic

.release/.changeset/poor-kings-compete.md, .release/.changeset/pre.json, apps/canonical-bridge-server/src/app.module.ts, apps/canonical-bridge-server/src/common/constants/index.ts, apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/module/bridge/bridge.schedule.ts, apps/canonical-bridge-server/src/module/token/token.processor.ts, apps/canonical-bridge-server/src/module/token/token.schedule.ts, apps/canonical-bridge-server/src/shared/web3/web3.service.ts, apps/canonical-bridge-ui/package.json, apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/aggregator/adapters/cBridge/CBridgeAdapter.ts, packages/canonical-bridge-widget/src/modules/aggregator/shared/BaseAdapter.ts
=> fix: Handle adaptor errors

apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> chore: Display proper error messages

apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> chore: Remove error return value

apps/canonical-bridge-server/src/shared/web3/web3.service.ts
=> feat: Remove try catch

apps/canonical-bridge-server/src/app.module.ts, apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/module/token/token.processor.ts
=> fix: Remove cache time

apps/canonical-bridge-server/src/module/bridge/bridge.schedule.ts
=> feat: Update task execute interval

packages/canonical-bridge-widget/src/modules/transfer/BridgeRoutes.tsx, packages/canonical-bridge-widget/src/modules/transfer/hooks/useLoadingBridgeFees.ts
=> chore: Remove test code

packages/canonical-bridge-widget/src/core/locales/en.ts
=> chore: Remove full stop

packages/canonical-bridge-widget/src/modules/transfer/components/TransferButtonGroup/index.tsx
=> chore: Remove extra gap

packages/canonical-bridge-widget/src/core/locales/en.ts
=> chore: Add full stop back

apps/canonical-bridge-ui/token-config/mainnet/chains.ts
=> chore: Update klaytn rpc

apps/canonical-bridge-ui/token-config/mainnet/chains.ts
=> feat: Update kaia rpc info

packages/canonical-bridge-widget/src/modules/aggregator/adapters/meson/hooks/useTrc20.ts
=> fix: Fix infinite loop

packages/canonical-bridge-widget/src/modules/aggregator/adapters/meson/hooks/useGetTronAllowance.ts, packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionSummaryModal/TokenInfo.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionSummaryModal/TransferSummary.tsx
=> chore: Update amount styling

.release/.changeset/hot-knives-pay.md, .release/.changeset/pre.json, apps/canonical-bridge-server/src/shared/web3/web3.service.ts, apps/canonical-bridge-ui/package.json, common/config/rush/pnpm-lock.yaml, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/wallet/hooks/useEvmSwitchChain.tsx
Reverts bnb-chain/canonical-bridge#258
=> Revert "feat: Update binance wallet name"

apps/canonical-bridge-ui/pages/mainnet/index.tsx, packages/canonical-bridge-sdk/src/debridge/index.ts, packages/canonical-bridge-sdk/src/debridge/types/index.ts, packages/canonical-bridge-widget/src/CanonicalBridgeProvider.tsx, packages/canonical-bridge-widget/src/modules/transfer/hooks/useLoadingBridgeFees.ts
=> feat: Add debridge referral code for tracking

packages/canonical-bridge-sdk/src/debridge/index.ts
=> chore: Add referral code

apps/canonical-bridge-ui/package.json, common/config/rush/pnpm-lock.yaml
=> feat: Modify binance web3 wallet name

packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionSummaryModal/TokenInfo.tsx
=> fix: Fix styling

packages/canonical-bridge-sdk/src/debridge/index.ts
=> fix: Fix solana token check issue

apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts
=> chore: Hide eth tokens

packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionSummaryModal/FeeSummary.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionSummaryModal/TokenInfo.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionSummaryModal/TransferSummary.tsx
=> feat: Update confirmation popup amount styling

packages/canonical-bridge-sdk/src/adapters/stargate/adapter.ts, packages/canonical-bridge-widget/src/modules/transfer/BridgeRoutes.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ReceiveInfo/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/TransferOverview/index.tsx
=> fix: fix issues

packages/canonical-bridge-sdk/src/adapters/base/index.ts, packages/canonical-bridge-sdk/src/adapters/cBridge/adapter.ts, packages/canonical-bridge-sdk/src/adapters/deBridge/adapter.ts, packages/canonical-bridge-sdk/src/adapters/layerZero/adapter.ts, packages/canonical-bridge-sdk/src/adapters/layerZero/types.ts
=> feat: Use provider's icon

packages/canonical-bridge-widget/src/modules/transfer/components/ToTokenSection/index.tsx
=> fix: Update toToken explorer link

packages/canonical-bridge-widget/src/modules/aggregator/adapters/stargate/hooks/useGetStarGateFees.ts
=> feat: Stargate max decimals error message

apps/canonical-bridge-ui/pages/mainnet/index.tsx
=> fix: Fix type issue

packages/canonical-bridge-widget/src/modules/aggregator/adapters/stargate/hooks/useGetStarGateFees.ts
=> chore: Update stargate decimal error msg

apps/canonical-bridge-server/package.json, apps/canonical-bridge-server/src/module/token/token.service.ts, common/config/rush/pnpm-lock.yaml
=> fix: Avoid getting llama price exception

apps/canonical-bridge-server/src/module/bridge/bridge.module.ts, apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/module/token/token.processor.ts, apps/canonical-bridge-server/src/module/token/token.service.ts, apps/canonical-bridge-server/src/shared/util/util.service.ts
=> refactor: Move chain's utils to UtilService

apps/canonical-bridge-server/src/module/token/token.processor.ts
=> feat: Open fetchCoingeckoTokens task

.release/.changeset/curvy-dingos-end.md, .release/.changeset/pre.json, apps/canonical-bridge-server/src/module/token/token.service.ts, packages/canonical-bridge-sdk/CHANGELOG.md, packages/canonical-bridge-sdk/package.json, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json
=> feat: Always resolve price api to avoid error

.release/.changeset/modern-toys-give.md, .release/.changeset/pre.json, .release/.changeset/smooth-vans-work.md, apps/canonical-bridge-server/src/common/constants/chains.ts, apps/canonical-bridge-server/src/module/bridge/bridge.controller.ts, apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/module/bridge/bridge.service.ts, apps/canonical-bridge-server/src/module/token/token.controller.ts, apps/canonical-bridge-server/src/module/token/token.processor.ts, apps/canonical-bridge-server/src/module/token/token.service.ts, packages/canonical-bridge-sdk/CHANGELOG.md, packages/canonical-bridge-sdk/package.json, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/hooks/useTokenList.ts, packages/canonical-bridge-widget/src/modules/aggregator/hooks/useSelection.ts, packages/canonical-bridge-widget/src/modules/aggregator/hooks/useTokenUpperLimit.ts, packages/canonical-bridge-widget/src/modules/aggregator/providers/TokenPricesProvider.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/MaxLink.tsx, packages/canonical-bridge-widget/src/modules/transfer/hooks/usePriceValidation.ts
=> feat: use token price on ethereum if can not get the token price on specified chain

.release/.changeset/pre.json, .release/.changeset/short-ants-love.md, apps/canonical-bridge-server/src/common/constants/chains.ts, apps/canonical-bridge-server/src/module/token/token.processor.ts, apps/canonical-bridge-server/src/module/token/token.service.ts, apps/canonical-bridge-ui/token-config/mainnet/chains.ts, packages/canonical-bridge-sdk/CHANGELOG.md, packages/canonical-bridge-sdk/package.json, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/aggregator/hooks/useTokenUpperLimit.ts, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferConfirmButton.tsx
=> fix: Convert token price type to number

apps/canonical-bridge-server/src/module/token/token.service.ts
=> fix: Fix token price issue

.vscode/settings.json, apps/canonical-bridge-server/src/module/bridge/bridge.processor.ts, apps/canonical-bridge-server/src/module/token/token.service.ts
=> fix: Fix token price fallback issue

apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts
=> test: Test debridge timeout

apps/canonical-bridge-ui/token-config/mainnet/useTransferConfig.ts, packages/canonical-bridge-sdk/src/adapters/deBridge/index.ts
=> test: Test timeout

packages/canonical-bridge-sdk/src/adapters/deBridge/index.ts
=> test: Revert test case

.release/.changeset/large-years-cover.md, .release/.changeset/pre.json, apps/canonical-bridge-server/src/module/token/token.service.ts, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/CanonicalBridgeProvider.tsx, packages/canonical-bridge-widget/src/modules/aggregator/hooks/useSelection.ts, packages/canonical-bridge-widget/src/modules/transfer/components/TransferButtonGroup/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/hooks/useInputValidation.ts
=> feat: Add log for token price

.release/.changeset/pre.json, .release/.changeset/rich-carpets-marry.md, packages/canonical-bridge-sdk/CHANGELOG.md, packages/canonical-bridge-sdk/jest.config.js, packages/canonical-bridge-sdk/package.json, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferConfirmButton.tsx
=> fix: Use deBridge's own token symbol to prevent validation failures 

apps/canonical-bridge-server/.env.example, apps/canonical-bridge-server/src/common/constants/index.ts, apps/canonical-bridge-server/src/common/filters/all-exception.filter.ts
=> fix: Change timeout to 30s to avoid api exception

.release/.changeset/pre.json, .release/.changeset/weak-falcons-accept.md, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json
=> feat(canonical-bridge-widget): Fix negative rate

.github/workflows/release.yaml
=> chore: Add debug log

.release/package-lock.json
=> chore: Update lock file

.release/.changeset/pre.json, .release/.changeset/rude-humans-marry.md, apps/canonical-bridge-ui/pages/mainnet/index.tsx, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/CanonicalBridgeProvider.tsx, packages/canonical-bridge-widget/src/core/analytics/AnalyticsContext.tsx, packages/canonical-bridge-widget/src/core/analytics/EventEmitter.ts, packages/canonical-bridge-widget/src/core/analytics/events.ts, packages/canonical-bridge-widget/src/core/analytics/index.ts, packages/canonical-bridge-widget/src/core/analytics/types.ts, packages/canonical-bridge-widget/src/core/utils/gtm.ts, packages/canonical-bridge-widget/src/index.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/ChooseTokenModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/DestinationNetworkModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/components/SelectModal/SourceNetworkModal.tsx, packages/canonical-bridge-widget/src/modules/aggregator/hooks/useHandleTxFailure.ts, packages/canonical-bridge-widget/src/modules/transfer/components/Button/ExchangeChainButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Button/RefreshingButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Button/SwitchNetworkButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Button/TransferConfirmButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Button/WalletConnectButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/FromSection/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/Modal/TransactionApproveModal/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ReceiveInfo/RouteChangeButton.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/MaxLink.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/SendInput/index.tsx, packages/canonical-bridge-widget/src/modules/transfer/components/ToSection/index.tsx
=> feat: Support custom analytics

packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/aggregator/providers/TokenPricesProvider.tsx
=> fix: Arb eth token price

packages/canonical-bridge-sdk/CHANGELOG.md, packages/canonical-bridge-sdk/package.json, packages/canonical-bridge-sdk/src/core/index.ts, packages/canonical-bridge-widget/CHANGELOG.md, packages/canonical-bridge-widget/package.json, packages/canonical-bridge-widget/src/modules/transfer/hooks/useLoadingBridgeFees.ts
=> fix: Debridge route bridge issue
